### ISSUE TITLE
这个项目是准备模仿pro.ant.design吗？

### ISSUE THREAD

**Issue by tortorse** [vueComponent/ant-design-vue-awesome#1]
我们这边之前用iview(因为iview的某些设计元素和`Antd`类似)搭了一个类似的，但是因为缺乏基础组件一直没有更新了。希望能一起维护

如下图：
![image](https://user-images.githubusercontent.com/10540493/38906281-447397aa-42e8-11e8-8a08-191ddefadcc4.png)

**Comment by tangjinzhou** [comment]
欢迎欢迎  可以加QQ群 217490093 交流

**Comment by tortorse** [comment]
准备按照`pro.ant.design`的方式来做
