### ISSUE TITLE
希望本项目有一个贡献指南以及一些问题

### ISSUE THREAD

**Issue by tortorse** [vueComponent/ant-design-vue-awesome#2]
## 目的

统一贡献(提交代码)的方式，让后续加入的成员能够快速进行开发。

### 1. 目录结构

采用vue-cli生成的目录结构，并按照`pro.ant.design`的结构进行梳理

```bash
|- mock //mock server有关
|- public //编译后文件
|- src //源码
 |- assets //静态资源
 |- common //配置，如菜单
 |- components //组件
 |- e2e //端到端测试脚本相关
 |- layouts //项目本身的布局
 |- models //目前空缺
 |- routes	//Demo 页面
 |- services // 后端或API相关配置
 |- utils //内部工具
|- tests 测试脚本
```
几个问题：
1. 组件的文档是否也写在components下的`组件`目录里
2. 组件的测试用例是否写在components下的`组件`目录里

### 2. 编码要求

1. 要不要做类型验证？
2. 命名采用哪种方式？
组件的命名：PascalCase? kebab-case?

**Comment by a401554998** [comment]
既然是模仿就按照antd pro 走吧。希望尽快能把cli搭建起来
